package biblioteca_virtual;

import static biblioteca_virtual.Dashboard.Login;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JPanel;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JPanel {

    Connect conn;
    Connection reg;
    private Object password;

    public Login() {
        initComponents();

        conn = new Connect();
        reg = conn.getConnection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        fondo2 = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        labelPass = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pass = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JPanel();
        ingresar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JPanel();
        registrar = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        background.setMinimumSize(new java.awt.Dimension(750, 430));
        background.setPreferredSize(new java.awt.Dimension(750, 430));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo2.setBackground(new java.awt.Color(102, 102, 255));
        fondo2.setForeground(new java.awt.Color(255, 204, 204));
        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca_virtual/images/fondo2.jpg"))); // NOI18N
        fondo2.setText("jLabel1");
        background.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -50, 480, 450));

        IniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        IniciarSesion.setText("Iniciar Sesion");
        background.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 200, 40));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 210, 10));

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setBorder(null);
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailMousePressed(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        background.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 260, -1));

        labelPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPass.setText("Password");
        background.add(labelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 130, -1));

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setText("Email");
        background.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 60, -1));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 210, 10));

        pass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(153, 153, 153));
        pass.setBorder(null);
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passMousePressed(evt);
            }
        });
        background.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 210, -1));

        btnIngresar.setBackground(new java.awt.Color(63, 72, 204));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIngresarMousePressed(evt);
            }
        });

        ingresar.setBackground(new java.awt.Color(255, 255, 255));
        ingresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresar.setText("Ingresar");

        javax.swing.GroupLayout btnIngresarLayout = new javax.swing.GroupLayout(btnIngresar);
        btnIngresar.setLayout(btnIngresarLayout);
        btnIngresarLayout.setHorizontalGroup(
            btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnIngresarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnIngresarLayout.setVerticalGroup(
            btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ingresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca_virtual/images/sesion.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 80, 100));

        btnregistrar.setBackground(new java.awt.Color(63, 72, 204));
        btnregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnregistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnregistrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnregistrarMousePressed(evt);
            }
        });

        registrar.setBackground(new java.awt.Color(255, 255, 255));
        registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrar.setText("Registrate");

        javax.swing.GroupLayout btnregistrarLayout = new javax.swing.GroupLayout(btnregistrar);
        btnregistrar.setLayout(btnregistrarLayout);
        btnregistrarLayout.setHorizontalGroup(
            btnregistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnregistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnregistrarLayout.setVerticalGroup(
            btnregistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnregistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrar)
                .addContainerGap())
        );

        background.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed

    }//GEN-LAST:event_emailActionPerformed

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        btnIngresar.setBackground(new Color(0, 156, 223));

    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        resetColor(btnIngresar);
    }//GEN-LAST:event_btnIngresarMouseExited

    //le doy aspecto de placeholder y cuando escribo se elimina la leyenda
    private void emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMousePressed
        /*
        if(email.getText().equals("Ingrese su email")){
         email.setText("");
         email.setForeground(Color.BLACK);
        }
       if (String.valueOf(pass.getPassword()).isEmpty()){
         pass.setText("********");
         pass.setForeground(Color.gray);
       }
         */
    }//GEN-LAST:event_emailMousePressed

    //le doy aspecto de placeholder y cuando escribo se elimina la leyenda
    private void passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMousePressed

    }//GEN-LAST:event_passMousePressed

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked

    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnregistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistrarMouseClicked

    private void btnregistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarMouseEntered
        btnregistrar.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_btnregistrarMouseEntered

    private void btnregistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarMouseExited
        resetColor(btnregistrar);
    }//GEN-LAST:event_btnregistrarMouseExited
/// boton registrar NUEVO me lleva a la pantalla para que se registre - FUNCIONA OK
    private void btnregistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarMousePressed
        UpUsers p1 = new UpUsers();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        Login.removeAll();
        Login.add(p1, BorderLayout.CENTER);
        Login.revalidate();
        Login.repaint();

    }//GEN-LAST:event_btnregistrarMousePressed

    //USUARIO REGISTRADO ingresa user and pass llega aca cuando clik en ingresar
    private void btnIngresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMousePressed

        // ACA FUNCIONA A MEDIAS - NO TIRA ERROR PERO NO VALIDA CON LA DB
        String usuario = email.getText();
        String password = pass.getText();
        boolean res = false;

        if (usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar usuario y password");
        } else {
            try {
                if (usuario.equals(email.getText()) && password.equals(pass.getText())) {
                    Statement stm = reg.createStatement();
                    ResultSet re = stm.executeQuery("SELECT 'email' 'pass' FROM `users` WHERE email = '" + email + "' AND pass= '" + pass + "' ");
                     if (re.next()) 
                     res = true;                   
                    
                     {

                        Users p1 = new Users();
                        p1.setVisible(true);
                        p1.setSize(750, 430);
                        p1.setLocation(0, 0);

                        Login.removeAll();
                        Login.add(p1, BorderLayout.CENTER);
                        Login.revalidate();
                        Login.repaint();
                     }
                   
                }
            } catch (SQLException ex) {
                javax.swing.JOptionPane.showMessageDialog(null, "Usuario o password incorrecto");

            }
        }

    }//GEN-LAST:event_btnIngresarMousePressed

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseEntered

    private void emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnIngresar;
    private javax.swing.JPanel btnregistrar;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelPass;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel registrar;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void resetColor(JPanel btnIngresar) {
        btnIngresar.setBackground(new Color(18, 90, 173));
    }
}

