/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca_virtual;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static biblioteca_virtual.Dashboard.Login;
/**
 *
 * @author Antonio
 */
public class UpBooks extends javax.swing.JPanel {

    Connect conn;
    Connection reg;
    boolean edition;
    String origId;
    /**
     * Creates new form Principal
     */
    public UpBooks() {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        edition = false;
    }
    
    public UpBooks(String bid, String btitle, String bauthor, String bcategory, String bstock, String bavai){
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        edition = true;
        
        origId = bid;
        id.setText(bid);
        title.setText(btitle);
        author.setText(bauthor);
        category.setText(bcategory);
        stock.setText(bstock);
        available.setText(bavai);
        
        jLabel1.setText("Guardar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text8 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        Text9 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        Text13 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        available = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        Text15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Subir nuevo Libro");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 350));

        button.setBackground(new java.awt.Color(63, 72, 204));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subir");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 30));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 260, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("ISBN");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        id.setForeground(new java.awt.Color(102, 102, 102));
        id.setText("Ingrese el ISBN del Libro");
        id.setBorder(null);
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idMousePressed(evt);
            }
        });
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 260, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Título");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        title.setForeground(new java.awt.Color(102, 102, 102));
        title.setText("Ingrese el Título");
        title.setBorder(null);
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleMousePressed(evt);
            }
        });
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 260, 10));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Autor");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        author.setForeground(new java.awt.Color(102, 102, 102));
        author.setText("Ingrese el nombre del Autor/es");
        author.setBorder(null);
        author.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                authorMousePressed(evt);
            }
        });
        author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorActionPerformed(evt);
            }
        });
        add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 260, 10));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Genero");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        category.setForeground(new java.awt.Color(102, 102, 102));
        category.setText("Ingrese el genero del Libro");
        category.setBorder(null);
        category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                categoryMousePressed(evt);
            }
        });
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 260, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 260, 10));

        Text13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text13.setText("Stock");
        add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        stock.setForeground(new java.awt.Color(102, 102, 102));
        stock.setText("Cantidad Total");
        stock.setBorder(null);
        stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stockMousePressed(evt);
            }
        });
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 80, 30));

        jSeparator14.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator14.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 80, 10));

        available.setForeground(new java.awt.Color(102, 102, 102));
        available.setText("Cantidad a prestar");
        available.setBorder(null);
        available.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                availableMousePressed(evt);
            }
        });
        available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableActionPerformed(evt);
            }
        });
        add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 100, 30));

        jSeparator16.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator16.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 100, 10));

        Text15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text15.setText("Disponibles");
        add(Text15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    private void idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMousePressed
       if(id.getText().equals("Ingrese el ISBN del Libro"))
        id.setText("");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
 
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese el genero del Libro");

       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       
    }//GEN-LAST:event_idMousePressed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void titleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMousePressed
        if(title.getText().equals("Ingrese el Título"))
        title.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ISBN del Libro");
   
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese el genero del Libro");

       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       
    }//GEN-LAST:event_titleMousePressed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void dateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMousePressed
        
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ISBN del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese el genero del Libro");
     
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
     
    }//GEN-LAST:event_dateMousePressed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }
    
    private void authorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorMousePressed
        if(author.getText().equals("Ingrese el nombre del Autor/es"))
        author.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ISBN del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
  
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
 
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       
    }//GEN-LAST:event_authorMousePressed

    private void authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorActionPerformed

    private void categoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryMousePressed
        if(category.getText().equals("Ingrese el genero del Libro"))
        category.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ISBN del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
     
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
   if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
     
    }//GEN-LAST:event_categoryMousePressed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void stockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMousePressed
        if(stock.getText().equals("Cantidad Total"))
        stock.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ISBN del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
  
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese el genero del Libro");
  
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
      
    }//GEN-LAST:event_stockMousePressed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    private void availableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableMousePressed
        if(available.getText().equals("Cantidad a prestar"))
        available.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ISBN del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");

       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese el genero del Libro");
 
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
      
    }//GEN-LAST:event_availableMousePressed

    private void availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableActionPerformed

    // SUBIR
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        if(id.getText().equals("Ingrese el ISBN del Libro") || title.getText().equals("Ingrese el Título")
           /* || date.getText().equals("Ingrese la Fecha de Publicación") */ || author.getText().equals("Ingrese el nombre del Autor/es")
            || category.getText().equals("Ingrese el genero del Libro")|| 
          
                stock.getText().equals("Cantidad Total")
            || available.getText().equals("Cantidad a prestar")){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            id.requestFocus();
        }
        else
        {
            String bid = id.getText();
            String btitle = title.getText();
         //   String bdate = date.getText();
            String bathor = author.getText();
            String bcategory = category.getText();
        
            String bstock = stock.getText();
            String bavailable = available.getText();
        //    String bejem = ejem.getText();
      //      int pag=0;
            int stc=0;
            int av=0;

            if(bid == null || "".equals(bid) || btitle == null || "".equals(btitle) || /* bdate == null || "".equals(bdate) 
                    || */ bathor == null || "".equals(bathor) || bcategory == null || "".equals(bcategory) 
                    || /* bedit == null || "".equals(bedit) || blang == null || "".equals(blang) || bpages == null || "".equals(bpages) 
                    || bdescr == null || "".equals(bdescr) || */ bstock == null || "".equals(bstock) 
                    || bavailable == null || "".equals(bavailable) ){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                id.requestFocus();
            }
            else{ 
                try{
               //     
                    stc = Integer.parseInt(bstock);
                    av = Integer.parseInt(bavailable);

                    try {
                        if(edition)
                            EditBook(bid, btitle, bathor, bcategory, stc, av);
                     //    EditBook(bid, btitle, bdate, bathor, bcategory, bedit, blang, pag, bdescr, stc, av, bejem);
                        else
                            InsertBook(bid, btitle, bathor, bcategory, stc, av);
                     //InsertBook(bid, btitle, bdate, bathor, bcategory, bedit, blang, pag, bdescr, stc, av, bejem);

                        id.setText("");
                        title.setText("");
                //        date.setText("");
                        author.setText("");
                        category.setText("");
              
                        stock.setText("");
                        available.setText("");
                       

                        if(edition){
                            Books p1 = new Books();
                            p1.setSize(750, 430);
                            p1.setLocation(5, 5);

                            Login.removeAll();
                            Login.add(p1, BorderLayout.CENTER);
                            Login.revalidate();
                            Login.repaint();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(UpUsers.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }catch(NumberFormatException ex){
                    javax.swing.JOptionPane.showMessageDialog(this, "El Stock y el Disponible, deben ser números enteros. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    id.requestFocus();
                }

            }
        }
    }//GEN-LAST:event_buttonMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    public void InsertBook(String id, String titu, String auth, String cate, int stck, int avai) throws SQLException{
 //       (String id, String titu, String fech, String auth, String cate, String ed, String idiom, int pags, String desc, int stck, int avai, String ej) throws SQLException{
        Statement stm = reg.createStatement();
        
        stm.executeUpdate("INSERT INTO `books` (`id`, `title`, `author`, `category`, `stock`, `available`) VALUES ('"+id+"', '"+titu+"', '"+ auth +"', '"+cate+"', '"+stck+"', '"+avai+"')");
      //     stm.executeUpdate("INSERT INTO `books` (`id`, `title`, `date`, `author`, `category`, `edit`, `lang`, `pages`, `description`, `ejemplares`, `stock`, `available`) VALUES ('"+id+"', '"+titu+"', '"+ fech +"', '"+ auth +"', '"+cate+"', '"+ed+"', '"+idiom+"', '"+pags+"', '"+desc+"', '"+ej+"', '"+stck+"', '"+avai+"')");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Libro registrado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }
    
    public void EditBook(String id, String titu, String auth, String cate, int stck, int avai) throws SQLException{
        Statement stm = reg.createStatement();
        
        stm.executeUpdate("UPDATE `books` SET `id` = '"+id+"', `title` = '"+titu+"', `author` = '"+auth+"', `category` = '"+cate+"', `stock` = '"+stck+"', `available` = '"+avai+"' WHERE `id` = '"+ origId +"';");
      // stm.executeUpdate("UPDATE `books` SET `id` = '"+id+"', `title` = '"+titu+"', `date` = '"+fech+"', `author` = '"+auth+"', `category` = '"+cate+"', `edit` = '"+ed+"', `lang` = '"+idiom+"', `pages` = '"+pags+"', `description` = '"+desc+"', `ejemplares` = '"+ej+"', `stock` = '"+stck+"', `available` = '"+avai+"' WHERE `id` = '"+ origId +"';");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Libro editado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text15;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField author;
    private javax.swing.JTextField available;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button;
    private javax.swing.JTextField category;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
