
package biblioteca_virtual;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import java.sql.Statement;
import static biblioteca_virtual.Dashboard.Login;

public class UpUsers extends javax.swing.JPanel {

    Connect conn;
    Connection reg;
    boolean edit;
    String idus;
    /**
     * Creates new form Principal
     */
    public UpUsers() {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        edit = false;
    }
    
    public UpUsers(String usid, String usname, String usap1, String usap2, String password) {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        idus = usid;
        name.setText(usname);
        ap1.setText(usap1);
        ap2.setText(usap2);
        pass.setText(password);
        
        
 
        edit = true;
        jLabel1.setText("Guardar");
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        ap1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        labelpass = new javax.swing.JLabel();
        ap2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        email = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pass = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Datos usuario");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 360));

        button.setBackground(new java.awt.Color(63, 72, 204));
        button.setToolTipText("");
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Guardar");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 260, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Nombre");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setText("Ingrese el nombre");
        name.setBorder(null);
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameMousePressed(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 260, 10));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Apellido");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        ap1.setForeground(new java.awt.Color(102, 102, 102));
        ap1.setText("Ingrese el apellido");
        ap1.setBorder(null);
        ap1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ap1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ap1MousePressed(evt);
            }
        });
        ap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap1ActionPerformed(evt);
            }
        });
        add(ap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 260, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 260, 10));

        labelpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelpass.setText("Password");
        add(labelpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        ap2.setForeground(new java.awt.Color(102, 102, 102));
        ap2.setText("Ingrese el email");
        ap2.setBorder(null);
        ap2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ap2MousePressed(evt);
            }
        });
        ap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap2ActionPerformed(evt);
            }
        });
        add(ap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 260, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 260, 10));

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("Email");
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 250, 10));

        pass.setForeground(new java.awt.Color(153, 153, 153));
        pass.setText("********");
        pass.setBorder(null);
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passMousePressed(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        button.setBackground(new Color (0,156,223));
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    private void nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMousePressed
        if(name.getText().equals("Ingrese el nombre"))
        name.setText("");
       if(ap1.getText().equals("") || ap1.getText() == null || ap1.getText().equals(" "))
        ap1.setText("Ingrese el apellido");
       if(ap2.getText().equals("") || ap2.getText() == null || ap2.getText().equals(" "))
        ap2.setText("Ingrese el email");
         if(pass.getPassword().equals("") || pass.getPassword() == null || pass.getPassword().equals(" "))
        pass.setText("********");
         
 
    }//GEN-LAST:event_nameMousePressed

    private void ap1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap1MousePressed
        if(!name.getText().equals("") && name.getText() != null && !name.getText().equals(" ")) {
        } else {
            name.setText("Ingrese el nombre");
        }
       if(ap1.getText().equals("Ingrese el apellido"))
        ap1.setText("");
       if(ap2.getText().equals("") || ap2.getText() == null || ap2.getText().equals(" "))
        ap2.setText("Ingrese el email");
       if(pass.getPassword().equals("") || pass.getPassword() == null || pass.getPassword().equals(" "))
        pass.setText("********");
 
    }//GEN-LAST:event_ap1MousePressed

    private void ap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap1ActionPerformed

    private void ap2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap2MousePressed
       if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
        name.setText("Ingrese el nombre");
       if(ap2.getText().equals("Ingrese el email"))
        ap2.setText("");
       if(ap1.getText().equals("") || ap1.getText() == null || ap1.getText().equals(" "))
        ap1.setText("Ingrese el apellido");
       if(pass.getPassword().equals("") || pass.getPassword() == null || pass.getPassword().equals(" "))
        pass.setText("********");
 /*      if(dom.getText().equals("") || dom.getText() == null || dom.getText().equals(" "))
        dom.setText("Ingrese el domicilio");
       if(tel.getText().equals("") || tel.getText() == null || tel.getText().equals(" "))
        tel.setText("Ingrese un número telefónico");
*/
    }//GEN-LAST:event_ap2MousePressed

    private void ap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed
    // REGISTRAR
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        if(name.getText().equals("Ingrese el nombre") || ap1.getText().equals("Ingrese el apellido")
            || ap2.getText().equals("Ingrese el email") || pass.getPassword().equals("********")
            
            ){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            name.requestFocus();
        }
        else
        {
            String uname = name.getText();
            String uapp = ap1.getText();
            String uapm = ap2.getText();
            String password;
            password = String.valueOf(pass.getPassword());
    
            
   

            if(uname == null || "".equals(uname) || uapp == null || "".equals(uapp) || uapm == null || "".equals(uapm) 
             || password == null || "".equals(password) // || "".equals(udom) || utel == null || "".equals(utel)
                    
                    ){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                name.requestFocus();
            }
            else{ 
                try {
                    if(edit)
                //        EditUser(idus, uname, uapp, uapm, udom, utel);
                        EditUser(idus, uname, uapp, uapm, password);
                    else
      
                        InsertUser(uname, uapp, uapm, password);

                    name.setText("");
                    ap1.setText("");
                    ap2.setText("");
                    pass.setText("");
    

                    if(edit){
                        Users p1 = new Users();
                        p1.setSize(750, 430);
                        p1.setLocation(0, 0);

                        Login.removeAll();
                        Login.add(p1, BorderLayout.CENTER);
                        Login.revalidate();
                        Login.repaint();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(UpUsers.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        }
    }//GEN-LAST:event_buttonMousePressed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void passMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseEntered
       
    }//GEN-LAST:event_passMouseEntered

    private void passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMousePressed
       if(name.getText().equals("") || name.getText() == null || name.getText().equals(" "))
        name.setText("Ingrese el nombre");
       if(ap2.getText().equals("Ingrese el email"))
        ap2.setText("");
       if(ap1.getText().equals("") || ap1.getText() == null || ap1.getText().equals(" "))
        ap1.setText("Ingrese el apellido");
       if(pass.getPassword().equals("") || pass.getPassword() == null || pass.getPassword().equals(" "))
        pass.setText("********");
       
    }//GEN-LAST:event_passMousePressed

    private void nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMouseEntered

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMouseClicked

    private void ap1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ap1MouseExited

    private void passMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_passMouseExited

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }

     public void InsertUser(String name, String app, String apm, String password) throws SQLException{
        Statement stm = reg.createStatement();
        
    
        stm.executeUpdate("INSERT INTO `users` (`name`, `last_name_p`, `email`, `pass` ) VALUES ('"+name+"','"+app+"','"+apm+"','"+password+"')");
       // stm.executeUpdate("INSERT INTO `users` (`name`, `last_name_p`, `email`, `pass` ) VALUES ('luciano','gaitan','lucianogaitan','123456')");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario registrado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }
    

       public void EditUser(String id, String name, String app, String apm, String pass) throws SQLException{
        Statement stm = reg.createStatement();
        
        stm.executeUpdate("UPDATE `users` SET `name` = '"+name+"', `last_name_p` = '"+app+"', `pass` = '"+pass+"', `email` = '"+apm+"' WHERE `id` = "+ id +";");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario editado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField ap1;
    private javax.swing.JTextField ap2;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelpass;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
